services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=frank
      - POSTGRES_DB=data_analysis
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: